"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!#8^d=@b09*&yf+_&8c$z9t(tfwhvossgf@d!k=$6gu#j9++o-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'api_v1',
]

AUTH_USER_MODEL = 'api_v1.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import socket

def check_mysql_availability(host='localhost', port=3306, timeout=1.0):
    """
    Check if MySQL driver is installed and if the port is open.
    """
    # 1. Check if MySQL driver is installed
    mysql_driver_installed = False
    try:
        import pymysql
        pymysql.install_as_MySQLdb()
        mysql_driver_installed = True
    except ImportError:
        try:
            import MySQLdb
            mysql_driver_installed = True
        except ImportError:
            pass

    if not mysql_driver_installed:
        return False, "MySQL driver (pymysql or mysqlclient) is not installed"

    # 2. Check if the port is open
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True, "MySQL port is open"
    except (socket.timeout, ConnectionRefusedError, OSError) as e:
        return False, f"MySQL port {port} is not accessible: {e}"

# Check MySQL status
import os
db_host = os.environ.get('DB_HOST', 'localhost')
db_port = int(os.environ.get('DB_PORT', '3306'))
mysql_available, reason = check_mysql_availability(host=db_host, port=db_port, timeout=5.0)
if os.environ.get('FORCE_SQLITE') == 'True':
    mysql_available = False
    reason = "Forced by FORCE_SQLITE environment variable"

if mysql_available:
    print(f"[Database] MySQL detected at {db_host}:{db_port}! Using MySQL database.")
    
    # 繞過 MariaDB 10.5+ 版本限制以相容 XAMPP (MariaDB 10.4.32)
    from django.db.backends.base.base import BaseDatabaseWrapper
    BaseDatabaseWrapper.check_database_version_supported = lambda self: None
    
    # 解決 MariaDB 10.4.x 不支援 RETURNING 語法導致新增資料報錯的問題
    from django.db.backends.mysql.features import DatabaseFeatures
    DatabaseFeatures.can_return_columns_from_insert = property(
        lambda self: self.connection.mysql_is_mariadb and self.connection.mysql_version >= (10, 5, 0)
    )
    
    db_user = os.environ.get('DB_USER', 'root')
    db_password = os.environ.get('DB_PASSWORD', '')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'nojo',
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': str(db_port),
            'OPTIONS': {
                'charset': 'utf8mb4',
            }
        },
        'nojo_django_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'nojo_django_db',
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': str(db_port),
            'OPTIONS': {
                'charset': 'utf8mb4',
            }
        }
    }


else:
    print(f"[Database] Fallback to SQLite (Reason: {reason}).")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'nojo_django_db': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'nojo_django_db.sqlite3',
        }
    }

DATABASE_ROUTERS = ['core.router.DatabaseRouter']



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

