# Generated by Django 5.2.14 on 2026-06-05 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, db_column='birth_date', null=True)),
                ('credit_point', models.IntegerField(default=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='address_id', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('street_line', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(db_column='court_id', primary_key=True, serialize=False)),
                ('occupied', models.BooleanField(default=False)),
                ('base_price', models.IntegerField(db_column='base_price', default=0)),
            ],
            options={
                'db_table': 'court',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(db_column='facility_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.AutoField(db_column='rule_id', primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('no_show', 'No Show'), ('not_paid', 'Not Paid'), ('bad_behavior', 'Bad Behavior')], max_length=20, unique=True)),
                ('points_deducted', models.IntegerField()),
            ],
            options={
                'db_table': 'penalty_rules',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(db_column='sport_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='sport_name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'sports',
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='availability', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('available_dates', models.JSONField(default=list)),
                ('time_slots', models.JSONField(default=list)),
                ('preferred_city', models.CharField(max_length=50)),
                ('preferred_district', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('search_radius_km', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'user_availability',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(db_column='blacklist_id', primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='feedback_id', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('建議', '建議'), ('錯誤', '錯誤'), ('場地', '場地'), ('其他', '其他')], max_length=20)),
                ('content', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.AutoField(db_column='game_id', primary_key=True, serialize=False)),
                ('game_name', models.CharField(db_column='game_name', default='未命名球局', max_length=100)),
                ('least_players', models.IntegerField(default=1)),
                ('most_players', models.IntegerField()),
                ('target_level', models.CharField(choices=[('新手(CB可參加)', '新手(CB可參加)'), ('高手(BA可參加)', '高手(BA可參加)'), ('菁英(AS可參加)', '菁英(AS可參加)')], max_length=20)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.BooleanField(default=False)),
                ('cancel_deadline', models.DateTimeField()),
                ('match_status', models.CharField(choices=[('recruiting', 'Recruiting'), ('full', 'Full'), ('closed', 'Closed'), ('failed_to_start', 'Failed to Start')], default='recruiting', max_length=20)),
                ('weather', models.JSONField(blank=True, db_column='weather', null=True)),
                ('air_index', models.IntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('booking_status', models.CharField(choices=[('已佔到/已預約', '已佔到/已預約'), ('未佔到/未預約', '未佔到/未預約'), ('未確認', '未確認')], default='未佔到/未預約', max_length=20)),
                ('duration', models.CharField(default='2 小時', max_length=50)),
                ('game_note', models.TextField(blank=True, db_column='game_note', null=True)),
                ('gender_limit', models.CharField(default='不限', max_length=20)),
                ('venue_status', models.CharField(default='未確認', max_length=20)),
                ('venue_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(db_column='court_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api_v1.court')),
                ('creator', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.sport')),
            ],
            options={
                'db_table': 'gamesmatches',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(db_column='announcement_id', primary_key=True, serialize=False)),
                ('title', models.CharField(default='公告', max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api_v1.gamematch')),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='message')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api_v1.gamematch')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deducted', 'Deducted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('match', models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.gamematch')),
                ('offender', models.ForeignKey(db_column='offender_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, db_column='rule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.penaltyrule')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='sports',
            field=models.ManyToManyField(db_table='court_sports', related_name='courts', to='api_v1.sport'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(db_column='venue_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('types', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('semi-outdoor', 'Semi-Outdoor')], max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=8, max_digits=11, null=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='api_v1.address')),
                ('facilities', models.ManyToManyField(db_table='venue_facilities', related_name='venues', to='api_v1.facility')),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='api_v1.venue'),
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=1, default=25.0, max_digits=4)),
                ('rain_probability', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('aqi', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weather_data',
                'unique_together': {('city', 'district')},
            },
        ),
        migrations.CreateModel(
            name='CourtConflict',
            fields=[
                ('id', models.AutoField(db_column='conflict_id', primary_key=True, serialize=False)),
                ('court1', models.ForeignKey(db_column='court_id_1', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_1', to='api_v1.court')),
                ('court2', models.ForeignKey(db_column='court_id_2', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_2', to='api_v1.court')),
            ],
            options={
                'db_table': 'court_conflicts',
                'unique_together': {('court1', 'court2')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_games', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.gamematch')),
            ],
            options={
                'db_table': 'keep',
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.AutoField(db_column='list_id', primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api_v1.gamematch')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_participants',
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MatchWaitlist',
            fields=[
                ('id', models.AutoField(db_column='waitlist_id', primary_key=True, serialize=False)),
                ('queue_position', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('promoted', 'Promoted'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='api_v1.gamematch')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_waitlist',
                'unique_together': {('match', 'queue_position'), ('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserSportLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('C(初學者)', 'C(初學者)'), ('B(熟練)', 'B(熟練)'), ('A(高手)', 'A(高手)'), ('S(菁英)', 'S(菁英)')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.sport')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sport_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sport_levels',
                'unique_together': {('user', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteVenue',
            fields=[
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorite_venues', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.venue')),
            ],
            options={
                'db_table': 'favorite_venues',
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
