# Generated by Django 5.2.14 on 2026-06-06 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, db_column='birth_date', null=True)),
                ('credit_point', models.IntegerField(default=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('line_id', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='address_id', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('street_line', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(db_column='court_id', primary_key=True, serialize=False)),
                ('occupied', models.BooleanField(default=False)),
                ('base_price', models.IntegerField(db_column='base_price', default=0)),
            ],
            options={
                'db_table': 'court',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(db_column='facility_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.AutoField(db_column='rule_id', primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('no_show', 'No Show'), ('not_paid', 'Not Paid'), ('bad_behavior', 'Bad Behavior')], max_length=20, unique=True)),
                ('points_deducted', models.IntegerField()),
            ],
            options={
                'db_table': 'penalty_rules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(db_column='sport_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='sport_name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'sports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(db_column='blacklist_id', primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='feedback_id', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('建議', '建議'), ('錯誤', '錯誤'), ('場地', '場地'), ('其他', '其他')], max_length=20)),
                ('content', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedbacks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.AutoField(db_column='game_id', primary_key=True, serialize=False)),
                ('game_name', models.CharField(db_column='game_name', default='未命名球局', max_length=100)),
                ('least_players', models.IntegerField(default=1)),
                ('most_players', models.IntegerField()),
                ('target_level', models.CharField(choices=[('休閒', '休閒'), ('業餘', '業餘'), ('高手', '高手')], max_length=20)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.BooleanField(default=False)),
                ('cancel_deadline', models.DateTimeField()),
                ('match_status', models.CharField(choices=[('recruiting', 'Recruiting'), ('full', 'Full'), ('closed', 'Closed'), ('failed_to_start', 'Failed to Start')], default='recruiting', max_length=20)),
                ('weather', models.JSONField(blank=True, db_column='weather', null=True)),
                ('air_index', models.IntegerField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('已佔到/已預約', '已佔到/已預約'), ('未佔到/未預約', '未佔到/未預約'), ('未確認', '未確認')], default='未佔到/未預約', max_length=20)),
                ('game_note', models.TextField(blank=True, db_column='game_note', null=True)),
                ('gender_limit', models.CharField(default='不限', max_length=20)),
                ('announcements', models.TextField(blank=True, db_column='布告欄', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(db_column='court_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api_v1.court')),
                ('creator', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.sport')),
            ],
            options={
                'db_table': 'gamesmatches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='message')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api_v1.gamematch')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('detail', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deducted', 'Deducted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('match', models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.gamematch')),
                ('offender', models.ForeignKey(db_column='offender_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(db_column='reporter_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, db_column='rule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.penaltyrule')),
            ],
            options={
                'db_table': 'reports',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='court',
            name='sports',
            field=models.ManyToManyField(db_table='court_sports', related_name='courts', to='api_v1.sport'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(db_column='venue_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('types', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('semi-outdoor', 'Semi-Outdoor')], max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=8, max_digits=11, null=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='api_v1.address')),
                ('facilities', models.ManyToManyField(db_table='venue_facilities', related_name='venues', to='api_v1.facility')),
            ],
            options={
                'db_table': 'venues',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='api_v1.venue'),
        ),
        migrations.CreateModel(
            name='CourtConflict',
            fields=[
                ('id', models.AutoField(db_column='conflict_id', primary_key=True, serialize=False)),
                ('court1', models.ForeignKey(db_column='court_id_1', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_1', to='api_v1.court')),
                ('court2', models.ForeignKey(db_column='court_id_2', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_2', to='api_v1.court')),
            ],
            options={
                'db_table': 'court_conflicts',
                'managed': True,
                'unique_together': {('court1', 'court2')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_games', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.gamematch')),
            ],
            options={
                'db_table': 'keep',
                'managed': True,
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.AutoField(db_column='list_id', primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api_v1.gamematch')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_participants',
                'managed': True,
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserSportLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('C(初學者)', 'C(初學者)'), ('B(熟練)', 'B(熟練)'), ('A(高手)', 'A(高手)'), ('S(菁英)', 'S(菁英)')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.sport')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sport_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sport_levels',
                'managed': True,
                'unique_together': {('user', 'sport')},
            },
        ),
    ]
