# Generated by Django 6.0.5 on 2026-05-27 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('street_line', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_show', 'No Show'), ('not_paid', 'Not Paid'), ('bad_behavior', 'Bad Behavior')], max_length=20, unique=True)),
                ('points_deducted', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='matchparticipant',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='court',
            name='sports',
            field=models.ManyToManyField(db_table='court_sports', related_name='courts', to='api_v1.sport'),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='air_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersportlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='types',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('semi-outdoor', 'Semi-Outdoor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.court'),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='creator',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='match_status',
            field=models.CharField(choices=[('recruiting', 'Recruiting'), ('full', 'Full'), ('closed', 'Closed'), ('failed_to_start', 'Failed to Start')], default='recruiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='target_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('casual', 'Casual'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deducted', 'Deducted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersportlevel',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('casual', 'Casual'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='favoritegame',
            table='keep',
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='api_v1.address'),
        ),
        migrations.AddField(
            model_name='venue',
            name='facilities',
            field=models.ManyToManyField(db_table='venue_facilities', related_name='venues', to='api_v1.facility'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.penaltyrule'),
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_dates', models.JSONField(default=list)),
                ('time_slots', models.JSONField(default=list)),
                ('preferred_city', models.CharField(max_length=50)),
                ('preferred_district', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('search_radius_km', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=1, default=25.0, max_digits=4)),
                ('rain_probability', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('aqi', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('city', 'district')},
            },
        ),
        migrations.CreateModel(
            name='CourtConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_1', to='api_v1.court')),
                ('court2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_2', to='api_v1.court')),
            ],
            options={
                'unique_together': {('court1', 'court2')},
            },
        ),
        migrations.CreateModel(
            name='MatchWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('promoted', 'Promoted'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='api_v1.gamematch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'queue_position'), ('match', 'user')},
            },
        ),
    ]
