# Generated by Django 5.2.14 on 2026-06-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_composite_pks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematch',
            name='created_at',
        ),
    ]
