# Generated by Django 5.2.14 on 2026-06-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_remove_gamematch_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBulletin',
            fields=[
                ('id', models.AutoField(db_column='bulletin_id', primary_key=True, serialize=False)),
                ('title', models.CharField(default='公告', max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='api_v1.gamematch')),
            ],
            options={
                'db_table': 'game_bulletins',
                'managed': True,
            },
        ),
    ]
