# Generated by Django 5.2.14 on 2026-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_gamebulletin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematch',
            name='announcements',
        ),
    ]
