# Generated by Django 5.2.14 on 2026-06-08 12:05

from django.db import migrations, models

def add_venue_note_to_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'gamesmatches' 
                  AND COLUMN_NAME = 'venue_note'
            """)
            if cursor.fetchone()[0] == 0:
                cursor.execute("ALTER TABLE `gamesmatches` ADD COLUMN `venue_note` TEXT NULL")

def reverse_add_venue_note_to_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'gamesmatches' 
                  AND COLUMN_NAME = 'venue_note'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE `gamesmatches` DROP COLUMN `venue_note`")

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_remove_gamematch_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='venue_note',
            field=models.TextField(blank=True, db_column='venue_note', null=True),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='match_status',
            field=models.CharField(choices=[('recruiting', 'Recruiting'), ('full', 'Full'), ('closed', 'Closed'), ('started', 'Started'), ('failed_to_start', 'Failed to Start')], default='recruiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersportlevel',
            name='level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], max_length=20),
        ),
        migrations.RunPython(add_venue_note_to_mysql, reverse_add_venue_note_to_mysql),
    ]
