# Generated by Django 5.2.14 on 2026-06-08 17:22

from django.db import migrations, models

def drop_venue_note_from_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'gamesmatches' 
                  AND COLUMN_NAME = 'venue_note'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE `gamesmatches` DROP COLUMN `venue_note`")

def add_venue_note_to_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'gamesmatches' 
                  AND COLUMN_NAME = 'venue_note'
            """)
            if cursor.fetchone()[0] == 0:
                cursor.execute("ALTER TABLE `gamesmatches` ADD COLUMN `venue_note` TEXT NULL")

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_gamematch_venue_note_alter_gamematch_match_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematch',
            name='venue_note',
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='booking_status',
            field=models.CharField(choices=[('已確認/已預約', '已確認/已預約'), ('未借到場地', '未借到場地'), ('未確認', '未確認')], default='未確認', max_length=20),
        ),
        migrations.RunPython(drop_venue_note_from_mysql, add_venue_note_to_mysql),
    ]

