# Generated by Django 6.0.5 on 2026-06-08 20:04

import django.db.models.deletion
from django.db import migrations, models

def update_notification_fk_on_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute("ALTER TABLE `notification` DROP FOREIGN KEY `fk_notification_game`")
            except Exception:
                pass
            cursor.execute("ALTER TABLE `notification` ADD CONSTRAINT `fk_notification_game` FOREIGN KEY (`game_id`) REFERENCES `gamesmatches` (`game_id`) ON DELETE SET NULL")

def reverse_notification_fk_on_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute("ALTER TABLE `notification` DROP FOREIGN KEY `fk_notification_game`")
            except Exception:
                pass
            cursor.execute("ALTER TABLE `notification` ADD CONSTRAINT `fk_notification_game` FOREIGN KEY (`game_id`) REFERENCES `gamesmatches` (`game_id`) ON DELETE CASCADE")

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_remove_gamematch_venue_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='booking_status',
            field=models.CharField(choices=[('已佔到/已預約', '已佔到/已預約'), ('未佔到/未預約', '未佔到/未預約'), ('未確認', '未確認')], default='未確認', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api_v1.gamematch'),
        ),
        migrations.RunPython(update_notification_fk_on_mysql, reverse_notification_fk_on_mysql),
    ]

