# Generated by Django 6.0.5 on 2026-06-08 20:56

import django.utils.timezone
from django.db import migrations, models

def add_last_credit_update_to_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'users' 
                  AND COLUMN_NAME = 'last_credit_update'
            """)
            if cursor.fetchone()[0] == 0:
                cursor.execute("ALTER TABLE `users` ADD COLUMN `last_credit_update` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)")

def remove_last_credit_update_from_mysql(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'users' 
                  AND COLUMN_NAME = 'last_credit_update'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE `users` DROP COLUMN `last_credit_update`")

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_alter_gamematch_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_credit_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(add_last_credit_update_to_mysql, remove_last_credit_update_from_mysql),
    ]
