# Generated by Django 6.0.5 on 2026-06-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_user_last_credit_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(db_column='announcement_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photo', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='feedback_id', primary_key=True, serialize=False)),
                ('type', models.CharField(default='建議', max_length=50)),
                ('content', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedbacks',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='courtconflict',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='favoritegame',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gamebulletin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gamematch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matchparticipant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersportlevel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'managed': False},
        ),
    ]
