# Generated by Django 6.0.5 on 2026-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_announcement_feedback_alter_address_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'feedback_types',
                'managed': True,
            },
        ),
    ]
